// APPLICATION CODES
const CONNETION_ERROR = "CONNETION_ERROR"
const CONNETION_SUCCESS = "CONNETION_SUCCESS"
const USER_LOGIN_SUCCESS = "USER LOGIN SUCCESS"
const USER_LOGIN_ERROR = "USER DOESN'T EXISTS"
const USER_SIGNUP_ERROR = "USER ALREADY EXISTS"
const USER_SIGNUP_SUCCESS = "ACCOUNT CREATED SUCCESSFULLY"
const USER_LOGOUT = "USER LOGOUT"

// SERVER CODES
const SERVER_ERROR = "SERVER ERROR"
const INVALID_URL = "INVALID URL"
const APPLICAITON_RUNNING = "APPLICAITON RUNNING"

// TOKEN CODES
const INVALID_TOKEN = "INVALID TOKEN."
const TOKEN_EXPIRED = "TOKEN EXPIRED."
const INVALID_USER_ACCESS = "INVALID USER ACCESS."

// PROJECT
const LISTING_PROJECT_SUCCESS = "LISTING PROJECT SUCCESS"
const LISTING_PROJECT_ERROR = "LISTING PROJECT ERROR"
const GET_PROJECT_SUCCESS = "GET A PROJECT DATA"
const GET_PROJECT_ERROR = "UNABLE TO GET PROJECT DATA"
const CREATE_PROJECT_SUCCESS = "CREATED PROJECT SUCCESS"
const CREATE_PROJECT_ERROR = "CREATE PROJECT ERROR"
const UPDATE_PROJECT_SUCCESS = "UPDATED PROJECT SUCCESS"
const UPDATE_PROJECT_ERROR = "UPDATE PROJECT ERROR"
const DELETE_PROJECT_SUCCESS = "DELETE PROJECT SUCCESS"
const DELETE_PROJECT_ERROR = "DELETE PROJECT ERROR"
const PROJECT_REMOVED_ALREADY = "PROJECT REMOVED ALREADY"

// DEPARTMENT
const LISTING_DEPARTMENT_SUCCESS = "LISTING DEPARTMENT SUCCESS"
const LISTING_DEPARTMENT_ERROR = "LISTING DEPARTMENT ERROR"
const GET_DEPARTMENT_SUCCESS = "GET A DEPARTMENT DATA"
const GET_DEPARTMENT_ERROR = "UNABLE TO GET DEPARTMENT DATA"
const CREATE_DEPARTMENT_SUCCESS = "CREATED DEPARTMENT SUCCESS"
const CREATE_DEPARTMENT_ERROR = "CREATE DEPARTMENT ERROR"
const UPDATE_DEPARTMENT_SUCCESS = "UPDATED DEPARTMENT SUCCESS"
const UPDATE_DEPARTMENT_ERROR = "UPDATE DEPARTMENT ERROR"
const DELETE_DEPARTMENT_SUCCESS = "DELETE DEPARTMENT SUCCESS"
const DELETE_DEPARTMENT_ERROR = "DELETE DEPARTMENT ERROR"
const CREATE_DUPLICATE_DEPARTMENT_ERROR = "CREATE DUPLICATE DEPARTMENT ERROR"
const DEPARTMENT_REMOVED_ALREADY = "DEPARTMENT REMOVED ALREADY"

// EMPLOYEE
const LISTING_EMPLOYEE_SUCCESS = "LISTING EMPLOYEE SUCCESS"
const LISTING_EMPLOYEE_ERROR = "LISTING EMPLOYEE ERROR"
const GET_EMPLOYEE_SUCCESS = "GET A EMPLOYEE DATA"
const GET_EMPLOYEE_ERROR = "UNABLE TO GET EMPLOYEE DATA"
const CREATE_EMPLOYEE_SUCCESS = "CREATED EMPLOYEE SUCCESS"
const CREATE_EMPLOYEE_ERROR = "CREATE EMPLOYEE ERROR"
const UPDATE_EMPLOYEE_SUCCESS = "UPDATED EMPLOYEE SUCCESS"
const UPDATE_EMPLOYEE_ERROR = "UPDATE EMPLOYEE ERROR"
const DELETE_EMPLOYEE_SUCCESS = "DELETE EMPLOYEE SUCCESS"
const DELETE_EMPLOYEE_ERROR = "DELETE EMPLOYEE ERROR"
const CREATE_DUPLICATE_EMPLOYEE_ERROR = "CREATE DUPLICATE EMPLOYEE ERROR"
const EMPLOYEE_REMOVED_ALREADY = "EMPLOYEE REMOVED ALREADY"

const APPLY_FOR_LEAVE = "LEAVE APPLICATION SUBMITTED" 
const APPLY_FOR_LEAVE_ERROR = "LEAVE APPLICATION SUBMIT ERROR" 
const GET_USER_LEAVE_SUCCESS = "GET USER LEAVE SUCCESS"
const GET_USER_LEAVE_ERROR = "GET USER LEAVE ERROR"
const GET_ALL_USER_LEAVE_SUCCESS = "GET ALL USER LEAVE SUCCESS"
const GET_ALL_USER_LEAVE_ERROR = "GET ALL USER LEAVE ERROR"
const APPROVE_LEAVE_SUCCESS = "APPROVE LEAVE SUCCESS"
const APPROVE_LEAVE_ERROR = "APPROVE LEAVE ERROR"

module.exports = {
    CONNETION_SUCCESS,
    CONNETION_ERROR,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_ERROR,
    USER_SIGNUP_ERROR,
    USER_SIGNUP_SUCCESS,
    SERVER_ERROR,
    INVALID_URL,
    APPLICAITON_RUNNING,
    INVALID_TOKEN,
    TOKEN_EXPIRED,
    INVALID_USER_ACCESS,

    LISTING_PROJECT_SUCCESS,
    LISTING_PROJECT_ERROR,
    GET_PROJECT_SUCCESS,
    GET_PROJECT_ERROR,
    CREATE_PROJECT_SUCCESS,
    CREATE_PROJECT_ERROR,
    UPDATE_PROJECT_SUCCESS,
    UPDATE_PROJECT_ERROR,
    DELETE_PROJECT_SUCCESS,
    DELETE_PROJECT_ERROR,
    PROJECT_REMOVED_ALREADY,

    LISTING_DEPARTMENT_SUCCESS,
    LISTING_DEPARTMENT_ERROR,
    GET_DEPARTMENT_SUCCESS,
    GET_DEPARTMENT_ERROR,
    CREATE_DEPARTMENT_SUCCESS,
    CREATE_DEPARTMENT_ERROR,
    UPDATE_DEPARTMENT_SUCCESS,
    UPDATE_DEPARTMENT_ERROR,
    DELETE_DEPARTMENT_SUCCESS,
    DELETE_DEPARTMENT_ERROR,
    CREATE_DUPLICATE_DEPARTMENT_ERROR,
    DEPARTMENT_REMOVED_ALREADY,

    LISTING_EMPLOYEE_SUCCESS,
    LISTING_EMPLOYEE_ERROR,
    GET_EMPLOYEE_SUCCESS,
    GET_EMPLOYEE_ERROR,
    CREATE_EMPLOYEE_SUCCESS,
    CREATE_EMPLOYEE_ERROR,
    UPDATE_EMPLOYEE_SUCCESS,
    UPDATE_EMPLOYEE_ERROR,
    DELETE_EMPLOYEE_SUCCESS,
    DELETE_EMPLOYEE_ERROR,
    CREATE_DUPLICATE_EMPLOYEE_ERROR,
    EMPLOYEE_REMOVED_ALREADY,

    APPLY_FOR_LEAVE,
    APPLY_FOR_LEAVE_ERROR,
    GET_USER_LEAVE_SUCCESS,
    GET_USER_LEAVE_ERROR,
    GET_ALL_USER_LEAVE_SUCCESS,
    GET_ALL_USER_LEAVE_ERROR,
    APPROVE_LEAVE_SUCCESS,
    APPROVE_LEAVE_ERROR,
}